spring.application.name=api-gateway
server.port=8080

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Route /auth/** traffic directly to your auth-service
spring.cloud.gateway.routes[0].id=auth-service-route
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# --- ROUTE 2: Citizen Service ---
spring.cloud.gateway.routes[1].id=citizen-service-route
spring.cloud.gateway.routes[1].uri=lb://citizen-service
spring.cloud.gateway.routes[1].predicates=Path=/citizens/**
