server.port=8081

message=Configuration loaded from Config Server

test.property=Working

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=aditya
spring.datasource.password=aditya

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true