server.port=8087

spring.application.name=benefit-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/benefit_db
spring.datasource.username=aditya
spring.datasource.password=aditya
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# JWT
jwt.secret=ebc0d8f042817877c4c802d7326fb586842fab04d965e9745b4c4db9f6d7cf9e
jwt.expiration=3600000

# Actuator
management.endpoints.web.exposure.include=*